import type { Metadata } from "next";
import { Rubik_Distressed } from "next/font/google";
import { Web3Provider } from "@/provider/Web3Provider";
import Header from "@/components/layout/header-app";
import "./globals.css";


const rubikDistressed = Rubik_Distressed({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Web3Provider>
        <body
          className={`${rubikDistressed.className} antialiased flex flex-col items-center `}
        >
          <div className="w-full flex items-center flex-col container bg-[#f8f4ef] z-10 rounded px-4">
            <Header />
            <div className="h-[calc(100vh-80px)]  w-full flex flex-col container py-10">
              {children}
            </div>
          </div>
        </body>
      </Web3Provider>
    </html>
  );
}
